name: changeformer
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - asttokens=3.0.0=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - blas=1.0=mkl
  - brotli=1.0.9=h9c3ff4c_4
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2025.4.26=hbd8a1cb_0
  - certifi=2024.8.30=pyhd8ed1ab_0
  - cffi=1.14.4=py38ha312104_0
  - colorama=0.4.4=pyh9f0ad1d_0
  - comm=0.2.2=pyhd8ed1ab_0
  - cudatoolkit=10.2.89=h8f6ccaa_8
  - cudnn=7.6.5.32=h01f27c4_1
  - cycler=0.11.0=pyhd8ed1ab_0
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.4.1=py38h709712a_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - einops=0.3.2=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - executing=2.1.0=pyhd8ed1ab_0
  - expat=2.2.10=h9c3ff4c_0
  - ffmpeg=4.3.2=hca11adc_0
  - fontconfig=2.13.1=hba837de_1005
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.11.0=h70c0345_0
  - future=1.0.0=pyhd8ed1ab_0
  - gettext=0.19.8.1=hf34092f_1004
  - giflib=5.2.1=h7b6447c_0
  - glib=2.58.3=py38h73cb85d_1004
  - gmp=6.2.1=h2531618_2
  - gnutls=3.6.15=he1e5248_0
  - gst-plugins-base=1.14.5=h0935bb2_2
  - gstreamer=1.14.5=h36ae1b5_2
  - icu=64.2=he1b5a44_1
  - intel-openmp=2021.4.0=h06a4308_3561
  - ipykernel=6.20.2=pyh210e3f2_0
  - ipython=8.12.2=pyh41d4057_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jpeg=9d=h7f8727e_0
  - jupyter_client=7.1.2=pyhd8ed1ab_0
  - jupyter_core=5.7.2=pyh31011fe_1
  - kiwisolver=1.3.1=py38h2531618_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - libblas=3.9.0=12_linux64_mkl
  - libedit=3.1.20210910=h7f8727e_0
  - libffi=3.2.1=hf484d3e_1007
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgfortran-ng=7.5.0=ha8ba4b0_17
  - libgfortran4=7.5.0=ha8ba4b0_17
  - libgomp=9.3.0=h5101ec6_17
  - libiconv=1.15=h63c8f33_5
  - libidn2=2.3.2=h7f8727e_0
  - liblapack=3.9.0=12_linux64_mkl
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.19.1=h4ff587b_0
  - libsodium=1.0.18=h36c2ea0_1
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.2.0=h85742a9_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=2.32.1=h7f98852_1000
  - libuv=1.40.0=h7b6447c_0
  - libwebp=1.2.0=h89dd481_0
  - libwebp-base=1.2.0=h27cfd23_0
  - libxcb=1.13=h7f98852_1003
  - libxml2=2.9.10=hee79883_0
  - lz4-c=1.9.3=h295c915_1
  - magma=2.5.4=hfead8bd_4
  - matplotlib=3.4.3=py38h578d9bd_1
  - matplotlib-base=3.4.3=py38hbbc1b5f_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py38h7f8727e_0
  - mkl_fft=1.3.1=py38hd3c417c_0
  - mkl_random=1.2.2=py38h51133e4_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - nccl=2.14.3.1=h1a5f58c_0
  - ncurses=6.3=h7f8727e_2
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - nettle=3.7.3=hbbd107a_1
  - ninja=1.10.2=h4bd325d_0
  - numpy=1.21.2=py38h20f2e39_0
  - numpy-base=1.21.2=py38h79a1101_0
  - olefile=0.46=pyhd3eb1b0_0
  - openh264=2.1.1=h4ff587b_0
  - openssl=1.1.1l=h7f8727e_0
  - packaging=25.0=pyh29332c3_1
  - parso=0.8.4=pyhd8ed1ab_0
  - pcre=8.45=h9c3ff4c_0
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pip=21.2.4=py38h06a4308_0
  - platformdirs=4.3.6=pyhd8ed1ab_0
  - prompt-toolkit=3.0.48=pyha770c72_0
  - prompt_toolkit=3.0.48=hd8ed1ab_1
  - psutil=5.8.0=py38h497a2fe_1
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.3=pyhd8ed1ab_0
  - pycparser=2.22=pyhd8ed1ab_0
  - pygments=2.18.0=pyhd8ed1ab_0
  - pyparsing=3.0.6=pyhd8ed1ab_0
  - pyqt=5.9.2=py38h05f1152_4
  - python=3.8.0=h0371630_2
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.8=2_cp38
  - pytorch=1.10.1=py3.8_cuda10.2_cudnn7.6.5_0
  - pytorch-mutex=1.0=cuda
  - pyzmq=22.1.0=py38h2035c66_0
  - qt=5.9.7=h0c104cb_3
  - readline=7.0=h7b6447c_5
  - scipy=1.7.1=py38h292c36d_2
  - setuptools=58.0.4=py38h06a4308_0
  - sip=4.19.13=py38he6710b0_0
  - six=1.16.0=pyhd3eb1b0_0
  - sleef=3.5.1=h7f98852_1
  - sqlite=3.33.0=h62c20be_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - timm=0.4.12=pyhd8ed1ab_0
  - tk=8.6.11=h1ccaba5_0
  - torchaudio=0.10.1=py38_cu102
  - torchvision=0.11.2=py38_cu102
  - tornado=6.1=py38h497a2fe_1
  - tqdm=4.62.3=pyhd8ed1ab_0
  - traitlets=5.14.3=pyhd8ed1ab_0
  - typing_extensions=3.10.0.2=pyh06a4308_0
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - wheel=0.37.0=pyhd3eb1b0_1
  - x264=1!161.3030=h7f98852_1
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xz=5.2.5=h7b6447c_0
  - zeromq=4.3.4=h9c3ff4c_0
  - zlib=1.2.11=h7f8727e_4
  - zstd=1.4.9=haebb681_0
  - pip:
      - mouseinfo==0.1.3
      - mss==9.0.2
      - opencv-python==4.10.0.84
      - pillow==10.4.0
      - pyautogui==0.9.54
      - pygetwindow==0.0.9
      - pymsgbox==1.0.9
      - pyperclip==1.9.0
      - pyrect==0.2.0
      - pyscreeze==1.0.1
      - python3-xlib==0.15
      - pytweening==1.2.0
      - tifffile==2023.7.10
prefix: /home/jaehyeonpark/miniconda3/envs/changeformer
